repos:
  - repo: local
    hooks:
      - id: lint
        name: make lint
        entry: make lint
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: test
        name: make test
        entry: make test
        language: system
        pass_filenames: false
        stages: [pre-commit]
