[project]
name = "relmedner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SkyeAv", email = "skye.a.goetz@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "apache-beam>=2.76.0",
    "cyclopts>=4.25.2",
    "datasets>=5.0.1",
    "pydantic>=2.13.5",
    "pyyaml>=6.0.3",
]

[project.scripts]
relmedner = "relmedner.cli:APP"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-xdist>=3.8.0",
    "ruff>=0.16.7",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=relmedner --cov-report=term-missing -n auto"

[tool.ruff]
line-length = 150
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "W", "UP", "B"]
