from __future__ import annotations

import os
from typing import Any

import pytest

from relmedner.models import TrainingExample, YamlIngests
from relmedner.streams import DataStream
from relmedner.types import Script

requires_live_hf: pytest.MarkDecorator = pytest.mark.skipif(
    os.environ.get("RELMEDNER_LIVE_HF") != "1",
    reason="streams real bigbio/ehr_rel rows from the hub; set RELMEDNER_LIVE_HF=1 (wenceslaus) to run",
)


@requires_live_hf
def test_a_live_streamed_ehr_rel_row_dispatches_end_to_end() -> None:
    """the exact production path -- declared ingest tuple -> build_stream ->
    HuggingFaceParquetDataStream (the new source kind's real hub load) -> Script.REGISTRY
    dispatch -- must turn real hub rows into valid training examples. Hand-built rows cannot
    catch hub-side drift (the auto-convert parquet files are regenerated by the hub whenever the
    upstream script dataset changes), so this runs against the live refs/convert/parquet branch.
    Gated behind RELMEDNER_LIVE_HF=1 and wenceslaus-only.

    Everything that transitively imports `datasets` (registry -> hf_parquet, pipeline) is
    imported INSIDE the gated body so plain `pytest --collect-only` stays offline-safe.
    """
    from relmedner.hf_parquet import HuggingFaceParquetDataStream
    from relmedner.ingests import YamlIngestsParser
    from relmedner.pipeline import dispatch_args, dispatch_row
    from relmedner.registry import build_stream

    Ingests: YamlIngests = YamlIngestsParser().parse_ingests()
    source, payload = next(
        (dataset.source, dataset.to_tuple()[1])
        for dataset in Ingests.datasets
        if getattr(dataset.task, "name", None) == "EhrRelScript" and dataset.to_tuple()[1][3] == "ehr_rel_bigbio_pairs/train/0000.parquet"
    )
    stream: DataStream = build_stream(source, payload)
    assert isinstance(stream, HuggingFaceParquetDataStream)

    Name: str
    Task: tuple[Any, ...]
    Values: tuple[Any, ...]
    Shipped: list[tuple[str, tuple[Any, ...], TrainingExample]] = []
    rows = stream.rows()
    # the first hub rows rate below the ship bar (the viewer's first pair rates 0.4), so scan a
    # bounded prefix: the measured ship rate (2,535/3,741) guarantees a shipping row inside 30
    for _ in range(30):
        Name, (Task, Values) = next(rows)
        assert Name == "bigbio/ehr_rel"
        assert Task == ("script", "EhrRelScript", ("relations",))
        assert len(Values) == 3  # the declared columns_out projection: text_1, text_2, label
        Outputs, Example = Script.dispatch("EhrRelScript", (tuple(Task[2]), Values))
        assert Outputs == ("relations",)
        assert isinstance(Example, TrainingExample)
        if Example.relations:
            Shipped.append((Name, (Task, Values), Example))
            break
    assert Shipped, "no shipping row in the first 30 live rows; the threshold or the stream broke"

    Name, Streamed, Example = Shipped[0]
    assert Example.relations[0].name == "related_to"
    assert Example.relations[0].evidence == "asserted"
    assert Example.relations[0].negated is False
    # gliner2's containment rule must hold for a REAL hub row, not just fixtures
    for field in Example.relations[0].fields:
        assert field.value in Example.text, f"mention {field.value!r} does not occur in the text"

    # the pipeline's own dispatch wrapper must agree with the direct registry call above, and it
    # stamps the DECLARED weight (0.5 here, the corpus's first non-1.0 source) onto the example;
    # compare on the stamped copy, then pin the stamp itself
    Weights, EdgeTrusts = dispatch_args(Ingests)
    PipelineOutputs, PipelineExample = dispatch_row((Name, Streamed), Weights, EdgeTrusts)
    assert PipelineOutputs == ("relations",)
    assert PipelineExample == Example.model_copy(update={"weight": Weights[Name]})
    assert PipelineExample.weight == 0.5
